Add app plugin to demo Grafana instance
grafana/grafana-javascript-agent pull request #59
Opened 2022-10-14 17:17 UTC by connorlindsey

Provisions a locally running instance of the app plugin which is needed to run the plugin + js agent together for local development.

2022-10-17 08:32 UTC, bfmatei requested changes
I would suggest the following approach extremely similar to the dashboards provisioning:

- have a `infa/grafana/plugins` folder
   - plugins can be symlinked in this folder via `ln -s ../grafana-plugins/kwl-plugin infra/grafana/plugins/kwl-plugin` or similar
   - the folder should have an empty `.gitkeep` file be added to git before anything
   - the folder shoud be added to the appropriate ignore files (`.gitignore`, `.prettierignore`, `.eslintignore`) to ensure that anything we add to this folder in the future will not be committed nor checked by linters/code formatters

- have a `infa/grafana/plugins-provisioning` 
   - this folder should have a `plugins.yaml.sample` file that contains the content of `dev.yaml`
   - add `infra/grafana/plugins-provisioning/plugins.yaml` (note: no `.sample` at the end) to `.gitignore` to avoid having it committed by mistake

- have the following variables in the `.env` file:
   - `GRAFANA_PLUGINS_PATH=/var/lib/grafana/plugins`
   - `GRAFANA_PLUGINS_PATH_LOCAL=./infra/grafana/plugins`
   - `GRAFANA_PLUGINS_PROVISIONING_PATH=/etc/grafana/provisioning/plugins`
   - `GRAFANA_PLUGINS_PROVISIONING_PATH_LOCAL=./infra/grafana/plugins-provisioning`

- have `docker-compose.yaml` file updated with:
   ```
         - '${GRAFANA_PLUGINS_PROVISIONING_PATH_LOCAL}:${GRAFANA_PLUGINS_PROVISIONING_PATH}'
         - '${GRAFANA_PLUGINS_PATH_LOCAL}:${GRAFANA_PLUGINS_PATH}'
   ```

- update the readme with a "how to" about using plugins:
   - symlink the plugin folder
   - create `plugins.yaml` file
   - enjoy

This way we are not forcing users to have the plugin in a specific place in their filesystem and they need to opt-in to use it.

2022-10-17 13:01 UTC, connorlindsey commented
@bfmatei is it possible with the current setup to load multiple env files? I know this works with a Nextjs. So we could have .env and .env.local where the local one is gitignored. I was thinking people could override the path so that they aren’t forced to put the plugin in a specific location. I’d prefer that as it seems much simpler than the symlinking setup

2022-10-17 13:18 UTC, bfmatei commented
@connorlindsey Unfortunately no :(

`docker compose` mimics `docker run` behaviour and the latter is failing with a non-existing `.env` file.

If we are to declare an empty `.env.local` file and add it to `.gitignore`, it won't work as Git will not ignore the changes.

Also, defining the `plugins.yaml` file without providing a path to the plugin will cause Grafana to not start:
```
Failed to start grafana. error: app provisioning error: plugin not installed: "grafana-kowalski-app"
app provisioning error: plugin not installed: "grafana-kowalski-app"
```

:-/

2022-10-17 13:25 UTC, connorlindsey commented
Ahh okay, I'll get that updated today then, thanks for the detailed info on getting it working properly

2022-10-20 19:36 UTC, eskirk commented on infra/grafana/config/grafana.ini
> +enable = tempoServiceGraph tempoSearch tempoBackendSearch traceToMetrics traceqlEditor topNav
All lowercase for `topnav` to get it enabled 

```suggestion
enable = tempoServiceGraph tempoSearch tempoBackendSearch traceToMetrics traceqlEditor topnav
```

2022-10-21 07:31 UTC, bfmatei approved these changes
lgtm!

2022-10-21 13:11 UTC, connorlindsey commented on infra/grafana/plugins-provisioning/plugins.yaml.sample
> +  - type: grafana-kowalski-app
Good call, I'll move this to the development guide in the plugin repo.

2022-10-21 14:52 UTC, merged